name: Scrape webs

on:
    schedule:
        - cron: '0 */2 * * *'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js 18.12
              uses: actions/setup-node@v3
              with:
                  node-version: 18.12
            - name: Build
              run: npm ci
            - name: Scrape
              run: npm run scrape
            - name: Push
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email 'github-actions[bot]@users.noreply.github.com'
                  git commit -a -m "Update database"
                  git push origin main
